# 50.007 Machine Learning
## Group Project

# Part 1  
Report the precision, recall and F scores for the outputs for both datasets.

<u>EN dataset</u>:\
Number of entities in gold data: 802\
Number of entities in prediction: 1148\
\
Number of correct entities : 614\
Entity  precision: 0.5348\
Entity  recall: 0.7656\
Entity  F: 0.6297\
\
Number of correct sentiments : 448\
Sentiment  precision: 0.3902\
Sentiment  recall: 0.5586\
Sentiment  F: 0.4595

<u>FR dataset</u>:\
Number of entities in gold data: 238\
Number of entities in prediction: 1114\
\
Number of correct entities : 186\
Entity  precision: 0.1670\
Entity  recall: 0.7815\
Entity  F: 0.2751\
\
Number of correct sentiments : 79\
Sentiment  precision: 0.0709\
Sentiment  recall: 0.3319\
Sentiment  F: 0.1169

In [1]:
# import statements
import numpy as np
import math
import copy

In [2]:
# function that takes in the filename for the training data
# returns word_sequences, tag_sequences
#   - word_sequences is a list in the form: [ [x_1_1, x_1_2, ...], [x_2_1, x_2_2, ...], ... [x_m_1, x_m_2, ... ] ]
#   - tag_sequences is a list in the form: [ [y_1_1, y_1_2, ...], [y_2_1, y_2_2, ...], ... [y_m_1, y_m_2, ... ] ]
def read_training_data(training_filename):
    training_file = open(training_filename, "r", encoding="utf-8")
    
    word_sequences = []
    tag_sequences = []
    
    current_word_sequence = []
    current_tag_sequence = []
    
    for line in training_file:
        training_word_and_tag = line.strip().split(" ")
        
        # add the current word and tag to the current word sequence and current tag sequence
        if (len(training_word_and_tag) == 2):
            current_word_sequence += [training_word_and_tag[0]]
            current_tag_sequence += [training_word_and_tag[1]]
        
        # if the sentence ended (empty line), add the previous word sequence and tag sequence to the lists of
        # word sequences and tag sequences respectively.
        else:
            word_sequences += [copy.deepcopy(current_word_sequence)]
            tag_sequences += [copy.deepcopy(current_tag_sequence)]
            
            current_word_sequence = []
            current_tag_sequence = []
            
    # account for the last word sequence
    if (len(current_word_sequence) != 0):
        word_sequences += [copy.deepcopy(current_word_sequence)]
        tag_sequences += [copy.deepcopy(current_tag_sequence)]
        
    training_file.close()

    return word_sequences, tag_sequences

# *****************************************************************************************************************************

# function that takes in the filename for the test data
# returns the test data as a list in the form: [ [x1_1, x1_2, ...], [x2_1, x2_2, ...] ]
def read_test_data(test_filename):
    test_file = open(test_filename, "r", encoding="utf-8")
    
    test_word_sequences = []
    
    current_test_word_sequence = []

    for line in test_file:
        test_word = line.strip()
        
        # add current word to the current word sequence
        if (len(test_word) != 0):
            current_test_word_sequence += [test_word]
            
        # if sentence ended (len(test_word) == 0)
        else:
            test_word_sequences += [copy.deepcopy(current_test_word_sequence)]
            current_test_word_sequence = []
        
    # account for the last word sequence
    if (len(current_test_word_sequence) != 0):
        test_word_sequences += [copy.deepcopy(current_test_word_sequence)]

    test_file.close()

    return test_word_sequences

# *****************************************************************************************************************************

# function that takes in the filename of the training data and optional k value
# returns emission_dict, tags_list
#   - emission_dict[x][y] gives the value e(x|y)
def create_emission_dict_tags_list(training_filename, k=1):
    # emission_dict[x][y] gives the value e(x|y)
    emission_dict = {}
    
    # count_y_dict[y] gives the total number of words tagged as y
    count_y_dict = {} 

    # count_x_tagged_as_y_dict[x_i][y_j] gives the number of times each observed variable x_i
    # was tagged as state y_j in the training data
    count_x_tagged_as_y_dict = {}

    # read training data
    word_sequences, tags_sequences = read_training_data(training_filename)

    # fill up count_y_dict and count_x_tagged_as_y_dict
    for sequence_index in range(0, len(word_sequences)):
        for word_index in range(0, len(word_sequences[sequence_index])):
            x = word_sequences[sequence_index][word_index]
            y = tags_sequences[sequence_index][word_index]

            # account for creating dictionary entry for the first time
            if not(y in count_y_dict.keys()):
                count_y_dict[y] = 0

            count_y_dict[y] += 1

            # account for creating dictionary entry for the first time
            if not(x in count_x_tagged_as_y_dict.keys()): 
                count_x_tagged_as_y_dict[x] = {}
                
            if not(y in count_x_tagged_as_y_dict[x].keys()):
                count_x_tagged_as_y_dict[x][y] = 0

            count_x_tagged_as_y_dict[x][y] += 1
        
    tags_list = count_y_dict.keys()

    # fill up emission_dict
    for sequence_index in range(0, len(word_sequences)):
        for word_index in range(0, len(word_sequences[sequence_index])):
            x = word_sequences[sequence_index][word_index]
            y = tags_sequences[sequence_index][word_index]
        
            # account for creating dictionary entry for the first time
            if not(x in emission_dict.keys()):
                emission_dict[x] = {}

            emission_dict[x][y] = count_x_tagged_as_y_dict[x][y] / (count_y_dict[y] + k)
            
            # add entry for "START" and "END"
            emission_dict[x]["START"] = 0
            emission_dict[x]["END"] = 0

    # add entry for #UNK#
    emission_dict["#UNK#"] = {}
    
    for tag in tags_list: # iterate over all the tags used in training
        emission_dict["#UNK#"][tag] = k / (count_y_dict[tag] + k)

    return emission_dict, tags_list

# *****************************************************************************************************************************

# function that takes in emission_dict, tags_list, observed variable x and hidden state y
# returns emission parameter e(x|y)
def emission(emission_dict, tags_list, x, y):
    # if tag was not in training data
    if (not(y in tags_list)):
        print("This tag was not in the training data")
        result = 0

    # else if word was not in training data
    elif (not(x in emission_dict.keys())): # treat x as "#UNK#"
        result = emission_dict["#UNK#"][y] # result = k / (count_y_dict[y] + k)
        
    # else if word is was in training data
    else:
        # if x was never tagged as y before during training, the probability is 0
        if not(y in emission_dict[x].keys()):
            emission_dict[x][y] = 0

        result = emission_dict[x][y] 

    return result

# *****************************************************************************************************************************

# function that takes in a result filename, a lists of word sequences and a list of tag sequences
# writes the results to the file specified by the result filename
def write_result(result_filename, word_sequences, tag_sequences):
    result_file = open(result_filename, "w" ,encoding="utf-8")
    
    for sequence_index in range(0, len(word_sequences)):
        for word_index in range(0, len(word_sequences[sequence_index])):
            result_file.write(word_sequences[sequence_index][word_index] + " " + tag_sequences[sequence_index][word_index] + "\n")
        
        result_file.write("\n")

    result_file.close()

# *****************************************************************************************************************************
    
# function that takes in the training data filename, test data filename, result filename and optional k value
# produces the tag y* = arg_max_y e(x|y) for each word in the test data
# writes the results to the file specified by the result filename
def simple_sentiment_analysis(training_filename, test_filename, result_filename, k=1):    
    # initialise emission_dict
    emission_dict, tags_list = create_emission_dict_tags_list(training_filename, k)
    
    test_word_sequences = read_test_data(test_filename)
    
    prediction_tag_sequences = []

    for test_word_sequence in test_word_sequences:
        current_prediction_tag_sequence = []
        
        for test_word in test_word_sequence:
            # find the tag that gives the highest value for e(test_variable | tag)
            predicted_tag = ""
            highest_emission_value = 0

            for tag in tags_list:
                current_emission_value = emission(emission_dict, tags_list, test_word, tag)

                if current_emission_value > highest_emission_value:
                    highest_emission_value = current_emission_value
                    predicted_tag = tag

            current_prediction_tag_sequence += [predicted_tag]
            
        # at the end of the sentence, add the current prediction tag sequence to the lise prediction_tag_sequences
        prediction_tag_sequences += [copy.deepcopy(current_prediction_tag_sequence)]
        current_prediction_tag_sequence = []

    write_result(result_filename, test_word_sequences, prediction_tag_sequences)

    return test_word_sequences, prediction_tag_sequences, emission_dict

In [3]:
# perform prediction for the EN dataset
simple_sentiment_analysis("EN/train", "EN/dev.in", "EN/dev.p1.out")

# evaluate prediction for the EN dataset
!python "evalResult.py" "EN/dev.out" "EN/dev.p1.out"


#Entity in gold data: 802
#Entity in prediction: 1148

#Correct Entity : 614
Entity  precision: 0.5348
Entity  recall: 0.7656
Entity  F: 0.6297

#Correct Sentiment : 448
Sentiment  precision: 0.3902
Sentiment  recall: 0.5586
Sentiment  F: 0.4595


In [4]:
# perform prediction for the FR dataset
simple_sentiment_analysis("FR/train", "FR/dev.in", "FR/dev.p1.out")

# evaluate prediction for the FR dataset
!python "evalResult.py" "FR/dev.out" "FR/dev.p1.out"


#Entity in gold data: 238
#Entity in prediction: 1114

#Correct Entity : 186
Entity  precision: 0.1670
Entity  recall: 0.7815
Entity  F: 0.2751

#Correct Sentiment : 79
Sentiment  precision: 0.0709
Sentiment  recall: 0.3319
Sentiment  F: 0.1169


# Part 2
Report the precision, recall and F scores for the outputs for both datasets.

<u>EN dataset</u>:\
Number of entities in gold data: 802\
Number of entities in prediction: 793\
\
Number of correct entities : 554\
Entity  precision: 0.6986\
Entity  recall: 0.6908\
Entity  F: 0.6947\
\
Number of correct sentiments : 500\
Sentiment  precision: 0.6305\
Sentiment  recall: 0.6234\
Sentiment  F: 0.6270

<u>FR dataset</u>:\
Number of entities in gold data: 238\
Number of entities in prediction: 61\
\
Number of correct entities : 37\
Entity  precision: 0.6066\
Entity  recall: 0.1555\
Entity  F: 0.2475\
\
Number of correct sentiments : 20\
Sentiment  precision: 0.3279\
Sentiment  recall: 0.0840\
Sentiment  F: 0.1338

In [5]:
# function that takes in list of tag sequences in the form [ [y1_1, y1_2, ... ], [y2_1, y2_2, ...], ... ]
# returns transition_dict
#   - transition_dict[(tag1, tag2)] gives the transition parameter q(tag2 | tag1)
def create_transition_dict(input_list):
    # Create transition dict
    # ========================
    transition_dict = {}
    
    # Get list of tags
    tags = set([tag for sentence in input_list for tag in sentence])

    # Update probability for each instance of tag1 > tag2 inside transition_dict
    for tag1 in tags:
        for tag2 in tags:
            count = 0
            total = 0
            for sentence in input_list:
                total += len(sentence) - 1
                for i in range(len(sentence) - 1):
                    if sentence[i] == tag1 and sentence[i+1] == tag2:
                        count += 1
            if count > 0:
                transition_dict[(tag1, tag2)] = count / total
    
    # Create initial probability dict
    # ========================
    start_tag_count_dict = {}
    stop_tag_count_dict = {}
    
    # Get num of starting tags that appear
    for sentence in input_list:
        if sentence[0] not in start_tag_count_dict:
            start_tag_count_dict[sentence[0]] = 1
        else:
            start_tag_count_dict[sentence[0]] += 1
        
        if sentence[-1] not in stop_tag_count_dict:
            stop_tag_count_dict[sentence[-1]] = 1
        else:
            stop_tag_count_dict[sentence[-1]] += 1
    
    # Fill in initial prob dict with num of starting/ending tags divided by total sentence num
    for tag in start_tag_count_dict:
        transition_dict[('START',tag)] = start_tag_count_dict[tag] / len(input_list)
    for tag in stop_tag_count_dict:
        transition_dict[(tag,'STOP')] = stop_tag_count_dict[tag] / len(input_list)
    
    return transition_dict

# *****************************************************************************************************************************

# function that takes in transition_dict and the hidden states yi-1 and yi
# returns transition parameter q(yi|yi-1)
def transition(transition_dict, yi_minus_1, yi):
    if (yi_minus_1, yi) not in transition_dict.keys():
        transition_dict[(yi_minus_1, yi)] = 0

    result = transition_dict[(yi_minus_1, yi)]

    return result
    
# *****************************************************************************************************************************

# takes in a sequence of words, tags_list, emission_dict and transition_dict
# returns the most likely sequence of tags
def viterbi_first_order(word_sequence, tags_list, emission_dict, transition_dict):
    pi_dict = {}
    
    # =============================================================================================================================
    # initialization
    pi_dict[0] = {}
        
    pi_dict[0]["START"] = math.log(1)
    
    for word_index in range(1, len(word_sequence)+1): # index for each word in each sentence
        for tag in tags_list: # each tag
            if word_index not in pi_dict.keys():
                pi_dict[word_index] = {}

            pi_dict[word_index][tag] = float('-inf') # initialize pi(j, u) = 0 for all j and u

    # for the first word, transition from "START" to v
    x_1 = word_sequence[0]
    
    for v in tags_list:
        previous_pi_val = pi_dict[0]["START"]
        trans = transition(transition_dict, "START", v)
        emi = emission(emission_dict, tags_list, x_1, v)

        if trans != 0:
            log_trans = math.log(trans)
        else:
            log_trans = float('-inf')

        if emi != 0:
            log_emi = math.log(emi)
        else:
            log_emi = float('-inf')

        current_pi_val = previous_pi_val + log_trans + log_emi

        pi_dict[1][v] = current_pi_val
        
    # =============================================================================================================================
    # intermediate steps
    # for each observed variable
    for j in range(1, len(word_sequence)): # if len(word_sequence) == 1, this 'for loop' will not execute
        x_j_plus_1 = word_sequence[j] # refers to the j+1th word (to calculate emission)
        
        # for each hidden state v
        for v in tags_list:
            # pi(j+1, v) = max over all u { pi(j,u) * transition(u, v) * emissision(x_j_plus_1, v) }
            max_pi_val = float('-inf')
            
            for u in tags_list:
                previous_pi_val = pi_dict[j][u]
                trans = transition(transition_dict, u, v)
                emi = emission(emission_dict, tags_list, x_j_plus_1, v)

                if trans != 0:
                    log_trans = math.log(trans)
                else:
                    log_trans = float('-inf')
                
                if emi != 0:
                    log_emi = math.log(emi)
                else:
                    log_emi = float('-inf')
                
                current_pi_val = previous_pi_val + log_trans + log_emi

                # save the value that maximises
                if (current_pi_val > max_pi_val):
                    max_pi_val = current_pi_val
        
            pi_dict[j+1][v] = max_pi_val
    
    # =============================================================================================================================
    # final step
    max_pi_val = float('-inf')
    
    # for each hidden state u
    for u in tags_list:
        previous_pi_val = pi_dict[len(word_sequence)][u]
        trans = transition(transition_dict, u, "STOP")
        
        if trans != 0:
            log_trans = math.log(trans)
        else:
            log_trans = float('-inf')

        current_pi_val = previous_pi_val + log_trans
        
        # save the value that maximises
        if (current_pi_val > max_pi_val):
            max_pi_val = current_pi_val
        
    pi_dict[len(word_sequence) + 1] = {}
    pi_dict[len(word_sequence) + 1]["STOP"]  = max_pi_val
    
    # =============================================================================================================================
    # BACKTRACKING
    decoding_list = []
    # check final layer argmax
    argmax = float('-inf')
    currentmax = float('-inf')
    argmax_tag = "NO_TAG_FOUND"
    
    # start from last variable
    for u in tags_list:
        pi = pi_dict[len(word_sequence)][u]
        trans = transition(transition_dict, u, "STOP")
        
        if trans != 0:
            log_trans = math.log(trans)
        else:
            log_trans = float("-inf")
        
        currentmax = pi + log_trans
        
        if currentmax > argmax:
            argmax = currentmax
            argmax_tag = u
        
    decoding_list.append(argmax_tag)
    
    # Backtrack rest of pi_dict
    for j in range(len(word_sequence)-1, 0, -1): # if len(word_sequence) == 1, this 'for loop' will not execute
        
        argmax = float('-inf')
        currentmax = 0
        argmax_index = 0
    
        for u in tags_list:
    
            pi = pi_dict[j][u]
            trans = transition(transition_dict, u, decoding_list[-1])
            
            if trans != 0:
                log_trans = math.log(trans)
            else:
                log_trans = float("-inf")

            currentmax = pi + log_trans

            if currentmax > argmax:
                argmax = currentmax
                argmax_tag = u
        
        decoding_list.append(argmax_tag)
        
    decoding_list = decoding_list[::-1]
    
    return decoding_list

# *****************************************************************************************************************************

# function that takes in a training filename, test filename and result filename
# performs viterbi algorithm to assign the most likely sequence of tags to each sequence of words in the test file
# writes the results to the file specified by the result filename
def viterbi_first_order_prediction(training_filename, test_filename, result_filename, k=1):
    training_word_sequences, training_tag_sequences = read_training_data(training_filename)
    test_word_sequences = read_test_data(test_filename)
    
    emission_dict, tags_list = create_emission_dict_tags_list(training_filename, k)
    transition_dict = create_transition_dict(training_tag_sequences)

    tag_sequences = []

    for i in range(len(test_word_sequences)):
        most_likely_tags = viterbi_first_order(test_word_sequences[i], tags_list, emission_dict, transition_dict)
        tag_sequences.append(most_likely_tags)
    
    # some words may still be tagged "NO_TAG_FOUND". For those words, select the tag that 
    # gives the highest emission value
    for sentence_index in range(0, len(test_word_sequences)):
        for word_index in range(0, len(test_word_sequences[sentence_index])):
            # check the tag that was predicted for each word
            checking_word = test_word_sequences[sentence_index][word_index]
            checking_tag = tag_sequences[sentence_index][word_index]

            if (checking_tag == "NO_TAG_FOUND"):
                new_predicted_tag = ""
                
                # if the tag is "NO_TAG_FOUND", select the tag that gives the highest emission values
                highest_emission_value = 0
                
                for tag in tags_list:
                    current_emission_value = emission(emission_dict, tags_list, checking_word, tag)

                    if current_emission_value > highest_emission_value:
                        highest_emission_value = current_emission_value
                        new_predicted_tag = tag
                
                tag_sequences[sentence_index][word_index] = new_predicted_tag

        
    write_result(result_filename, test_word_sequences, tag_sequences)
    
    return

In [6]:
# perform prediction for the EN dataset
viterbi_first_order_prediction("EN/train", "EN/dev.in", "EN/dev.p2.out")

# evaluate prediction for the EN dataset
!python "evalResult.py" "EN/dev.out" "EN/dev.p2.out"


#Entity in gold data: 802
#Entity in prediction: 793

#Correct Entity : 554
Entity  precision: 0.6986
Entity  recall: 0.6908
Entity  F: 0.6947

#Correct Sentiment : 500
Sentiment  precision: 0.6305
Sentiment  recall: 0.6234
Sentiment  F: 0.6270


In [7]:
# perform prediction for the FR dataset
viterbi_first_order_prediction("FR/train", "FR/dev.in", "FR/dev.p2.out")

# evaluate prediction for the FR dataset
!python "evalResult.py" "FR/dev.out" "FR/dev.p2.out"


#Entity in gold data: 238
#Entity in prediction: 61

#Correct Entity : 37
Entity  precision: 0.6066
Entity  recall: 0.1555
Entity  F: 0.2475

#Correct Sentiment : 20
Sentiment  precision: 0.3279
Sentiment  recall: 0.0840
Sentiment  F: 0.1338


# Part 3
Report the precision, recall and F scores for the outputs for both datasets.\
\
<u>EN dataset</u>:\
Number of entities in gold data: 802\
Number of entities in prediction: 933\
\
Number of correct entities : 535\
Entity  precision: 0.5734\
Entity  recall: 0.6671\
Entity  F: 0.6167\
\
Number of correct sentiments : 408\
Sentiment  precision: 0.4373\
Sentiment  recall: 0.5087\
Sentiment  F: 0.4703\
\
<u>FR dataset</u>:\
Number of entities in gold data: 238\
Number of entities in prediction: 460\
\
Number of correct entities : 161\
Entity  precision: 0.3500\
Entity  recall: 0.6765\
Entity  F: 0.4613\
\
Number of correct sentiments : 76\
Sentiment  precision: 0.1652\
Sentiment  recall: 0.3193\
Sentiment  F: 0.2178


In [8]:
# function that takes in an old dictionary with keys as tuples
# returns a new dictionary of dictionaries
#   - keys for the outer dictionaries are the first element of the tuples from the old dictionary
#   - keys for the inner dictionaries are the second element of the tuples from the old dictionary
def convert_tuple_dict_to_dict_of_dicts(tuple_dict):
    dict_of_dicts = {}
    
    for key in tuple_dict.keys():
        if key[0] not in dict_of_dicts:
            dict_of_dicts[key[0]] = {}
            
        dict_of_dicts[key[0]][key[1]] = tuple_dict[key]
        
    return dict_of_dicts

# *****************************************************************************************************************************

# function that takes in a list of tag sequences
# returns transition_dict_second_order
#   - transtition_dict_second_order[tag1][tag2][tag3] gives second order transition parameter q(tag3 | tag1, tag2)
def create_transition_dict_second_order(input_list):
    
    # Create transition dict
    # ========================
    transition_dict = {}
    
    for sentence in input_list:
        
        # ONLY RUN IF SENTENCE HAS MORE THAN 1 WORD
        if len(sentence) > 1:
            
            for i in range(len(sentence) - 2):

                current_state = sentence[i]
                next_state = sentence[i + 1]
                next_next_state = sentence[i + 2]

                if current_state not in transition_dict:
                    transition_dict[current_state] = {}

                if next_state not in transition_dict[current_state]:
                    transition_dict[current_state][next_state] = {}

                if next_next_state not in transition_dict[current_state][next_state]:       
                    transition_dict[current_state][next_state][next_next_state] = 0

                transition_dict[current_state][next_state][next_next_state] += 1

                
    for current_state in transition_dict:
        
        for next_state in transition_dict[current_state]:
            
            total_count = sum(transition_dict[current_state][next_state].values())
            
            for next_next_state in transition_dict[current_state][next_state]:
                transition_dict[current_state][next_state][next_next_state] /= total_count
    
    
    # Create initial probability dict for [START][START][TAG] and [TAG][STOP][STOP]
    # ========================
    start_tag_count_dict = {}
    stop_tag_count_dict = {}
    
    # Get num of starting tags that appear
    for sentence in input_list:
        if sentence[0] not in start_tag_count_dict:
            start_tag_count_dict[sentence[0]] = 1
        else:
            start_tag_count_dict[sentence[0]] += 1
        
        if sentence[-1] not in stop_tag_count_dict:
            stop_tag_count_dict[sentence[-1]] = 1
        else:
            stop_tag_count_dict[sentence[-1]] += 1
    
    # Fill in initial prob dict with num of starting/ending tags divided by total sentence num
    for tag in start_tag_count_dict:
        if 'START' not in transition_dict:
            transition_dict['START'] = {}
        if 'START' not in transition_dict['START']:
            transition_dict['START']['START'] = {}

        transition_dict['START']['START'][tag] = start_tag_count_dict[tag] / len(input_list)
    
    
    for tag in stop_tag_count_dict:
        if tag not in transition_dict:
            transition_dict[tag] = {}
        if 'STOP' not in transition_dict[tag]:
            transition_dict[tag]['STOP'] = {}
        
        transition_dict[tag]['STOP']['STOP'] = stop_tag_count_dict[tag] / len(input_list)
    
    # ========================
        
        
    # Create initial probability dict for [START][TAG][TAG] and [TAG][TAG][STOP]
    # ========================
    start_tag_count_dict = {}
    stop_tag_count_dict = {}
    
    sentence_w_one_word = {}
    
    # Get num of starting tags that appear
    for sentence in input_list:
        
        # ONLY RUN IF SENTENCE HAS MORE THAN 1 WORD
        if len(sentence) > 1:
            
            if sentence[0] not in start_tag_count_dict:
                start_tag_count_dict[sentence[0]] = {}

            if sentence[1] not in start_tag_count_dict[sentence[0]]:
                start_tag_count_dict[sentence[0]][sentence[1]] = 1
            else:
                start_tag_count_dict[sentence[0]][sentence[1]] += 1


            if sentence[-2] not in stop_tag_count_dict:
                stop_tag_count_dict[sentence[-2]] = {}

            if sentence[-1] not in stop_tag_count_dict[sentence[-2]]:
                stop_tag_count_dict[sentence[-2]][sentence[-1]] = 1
            else:
                stop_tag_count_dict[sentence[-2]][sentence[-1]] += 1
        
        else:
            # FOR SENTENCES WITH ONLY ONE WORD
            word = sentence[0]
            
            if word not in sentence_w_one_word:
                sentence_w_one_word[word] = 0
            sentence_w_one_word[word] += 1

    # Fill in initial prob dict with num of starting/ending tags divided by total sentence num
    for tag in start_tag_count_dict:
        for tag2 in start_tag_count_dict[tag]:
            
            if 'START' not in transition_dict:
                transition_dict['START'] = {}
            if tag not in transition_dict['START']:
                transition_dict['START'][tag] = {}
                
            transition_dict['START'][tag][tag2] = start_tag_count_dict[tag][tag2] / len(input_list)
        
    for tag in stop_tag_count_dict:
         for tag2 in stop_tag_count_dict[tag]:

            if tag not in transition_dict:
                transition_dict[tag] = {}
            if tag2 not in transition_dict[tag]:
                transition_dict[tag][tag2] = {}

            transition_dict[tag][tag2]['STOP'] = stop_tag_count_dict[tag][tag2] / len(input_list)
    
                
    # Fill in initial prob dict with sentences with only ONE WORD
    for tag in sentence_w_one_word:
        
        if tag not in transition_dict['START']:
            transition_dict['START'][tag] = {}
        if 'STOP' not in transition_dict['START'][tag]:
            transition_dict['START'][tag]['STOP'] = sentence_w_one_word[tag] / len(input_list)
            
    return transition_dict

# *****************************************************************************************************************************

# function that takes in transition_dict_second_order and the hidden states yi-2, yi-1 and yi
# returns transition parameter q(yi|yi-2, yi-1)
def transition_second_order(transition_dict_second_order, yi_minus_2, yi_minus_1, yi):
    if (yi_minus_2 not in transition_dict_second_order.keys()):
        transition_dict_second_order[yi_minus_2] = {}
    if (yi_minus_1 not in transition_dict_second_order[yi_minus_2].keys()):
        transition_dict_second_order[yi_minus_2][yi_minus_1] = {}
    if (yi not in transition_dict_second_order[yi_minus_2][yi_minus_1].keys()):
        transition_dict_second_order[yi_minus_2][yi_minus_1][yi] = 0

    result = transition_dict_second_order[yi_minus_2][yi_minus_1][yi]

    return result

# *****************************************************************************************************************************

# function that takes in a sequence of words, tags_list, emission_dict and transition_dict_second_order
# returns the most likely sequence of tags
def viterbi_second_order(word_sequence, tags_list, emission_dict, transition_dict_second_order):
    pi_dict = {}
    
    # =============================================================================================================================
    # initialization
    pi_dict[0] = {}
        
    pi_dict[0]["START"] = math.log(1)
    
    for word_index in range(1, len(word_sequence)+1): # index for each word in each sentence
        for tag in tags_list: # each tag
            if word_index not in pi_dict.keys():
                pi_dict[word_index] = {}

            pi_dict[word_index][tag] = float('-inf') # initialize pi(j, u) = 0 for all j and u

    # for the first word, transition from "START" to "START" to v
    x_1 = word_sequence[0]
    
    for v in tags_list:
        previous_pi_val = pi_dict[0]["START"]
        trans = transition_second_order(transition_dict_second_order, "START", "START", v)
        emi = emission(emission_dict, tags_list, x_1, v)

        if trans != 0:
            log_trans = math.log(trans)
        else:
            log_trans = float('-inf')

        if emi != 0:
            log_emi = math.log(emi)
        else:
            log_emi = float('-inf')

        current_pi_val = previous_pi_val + log_trans + log_emi

        pi_dict[1][v] = current_pi_val

    # for the second word, transition from "START" to u to v
    if (len(word_sequence) > 1):
        x_2 = word_sequence[1]

        for v in tags_list:
            # pi(2, v) = max over all u: { pi(1,u) * transition("START", u, v) * emissision(x_2, v) }
            max_pi_val = float('-inf')

            for u in tags_list:
                previous_pi_val = pi_dict[1][u]
                trans = transition_second_order(transition_dict_second_order, "START", u, v)
                emi = emission(emission_dict, tags_list, x_2, v)

                if trans != 0:
                    log_trans = math.log(trans)
                else:
                    log_trans = float('-inf')

                if emi != 0:
                    log_emi = math.log(emi)
                else:
                    log_emi = float('-inf')

                current_pi_val = previous_pi_val + log_trans + log_emi

                # save the value that maximizes
                if current_pi_val > max_pi_val:
                    max_pi_val = current_pi_val

            pi_dict[2][v] = max_pi_val

    # =============================================================================================================================
    # intermediate steps
    # for each observed variable
    for j in range(2, len(word_sequence)): # if len(word_sequence) <= 2, this 'for loop' will not execute
        x_j_plus_1 = word_sequence[j] # refers to the j+1th word (to calculate emission)
        
        # for each hidden state v
        for v in tags_list:
            # pi(j+1, v) = max over all t, u { pi(j,u) * transition(t, u, v) * emissision(x_j_plus_2, v) }
            max_pi_val = float('-inf')
            
            for t in tags_list:
                for u in tags_list:
                    previous_pi_val = pi_dict[j][u]
                    trans = transition_second_order(transition_dict_second_order, t, u, v)
                    emi = emission(emission_dict, tags_list, x_j_plus_1, v)

                    if trans != 0:
                        log_trans = math.log(trans)
                    else:
                        log_trans = float('-inf')
                    
                    if emi != 0:
                        log_emi = math.log(emi)
                    else:
                        log_emi = float('-inf')
                    
                    current_pi_val = previous_pi_val + log_trans + log_emi

                    # save the value that maximises
                    if (current_pi_val > max_pi_val):
                        max_pi_val = current_pi_val
        
            pi_dict[j+1][v] = max_pi_val
    
    # =============================================================================================================================
    # final step

    # pi(n+1, "STOP") = max over all t, u { pi(n, u) * transition(t, u, "STOP")}}
    max_pi_val = float('-inf')
    
    for t in tags_list:
        for u in tags_list:
            previous_pi_val = pi_dict[len(word_sequence)][u]
            trans = transition_second_order(transition_dict_second_order, t, u, "STOP")
            
            if trans != 0:
                log_trans = math.log(trans)
            else:
                log_trans = float('-inf')

            current_pi_val = previous_pi_val + log_trans
            
            # save the value that maximises
            if (current_pi_val > max_pi_val):
                max_pi_val = current_pi_val
        
    pi_dict[len(word_sequence) + 1] = {}
    pi_dict[len(word_sequence) + 1]["STOP"]  = max_pi_val
    
    # =============================================================================================================================
    # BACKTRACKING

    decoding_list = []

    # check final layer argmax
    argmax = float('-inf')
    currentmax = float('-inf')
    argmax_tag = "NO_TAG_FOUND"
    
    # start from last variable
    for u in tags_list:
        pi = pi_dict[len(word_sequence)][u]
        trans = transition_second_order(transition_dict_second_order, u, "STOP", "STOP")
        
        if trans != 0:
            log_trans = math.log(trans)
        else:
            log_trans = float("-inf")
        
        currentmax = pi + log_trans
        
        if currentmax > argmax:
            argmax = currentmax
            argmax_tag = u
        
    decoding_list.append(argmax_tag)

    # continue with second last variable
    if (len(word_sequence) > 1):
        argmax = float('-inf')
        currentmax = float('-inf')
        argmax_tag = "NO_TAG_FOUND"

        for u in tags_list:
            pi = pi_dict[len(word_sequence)-1][u]
            trans = transition_second_order(transition_dict_second_order, u, decoding_list[-1], "STOP")
            
            if trans != 0:
                log_trans = math.log(trans)
            else:
                log_trans = float("-inf")
            
            currentmax = pi + log_trans
            
            if currentmax > argmax:
                argmax = currentmax
                argmax_tag = u
            
        decoding_list.append(argmax_tag)
    
    # Backtrack rest of pi_dict
    for j in range(len(word_sequence)-2, 0, -1): # if len(word_sequence) <= 2, this 'for loop' will not execute
        argmax = float('-inf')
        currentmax = 0
        argmax_index = 0
    
        for u in tags_list:
            pi = pi_dict[j][u]
            trans = transition_second_order(transition_dict_second_order, u, decoding_list[-1], decoding_list[-2])
            
            if trans != 0:
                log_trans = math.log(trans)
            else:
                log_trans = float("-inf")

            currentmax = pi + log_trans

            if currentmax > argmax:
                argmax = currentmax
                argmax_tag = u
        
        decoding_list.append(argmax_tag)
        
    decoding_list = decoding_list[::-1]
    
    return decoding_list

# *****************************************************************************************************************************

# function that takes in the training data filename, test data filename, result filename and optional k value
# performs second order viterby algorithm to assign the most likely tag sequence for each sentence in the test data
# writes the results to the file specified by the result filename
def viterbi_second_order_prediction(training_filename, test_filename, result_filename, k=1):
    training_word_sequences, training_tag_sequences = read_training_data(training_filename)
    test_word_sequences = read_test_data(test_filename)
    
    emission_dict, tags_list = create_emission_dict_tags_list(training_filename, k)
    transition_dict_second_order = create_transition_dict_second_order(training_tag_sequences)

    tag_sequences = []

    for i in range(len(test_word_sequences)):
        most_likely_tags = viterbi_second_order(test_word_sequences[i], tags_list, emission_dict, transition_dict_second_order)
        tag_sequences.append(most_likely_tags)
    
    # some words may still be tagged "NO_TAG_FOUND". For those words, select the tag that 
    # gives the highest emission value
    for sentence_index in range(0, len(test_word_sequences)):
        for word_index in range(0, len(test_word_sequences[sentence_index])):
            # check the tag that was predicted for each word
            checking_word = test_word_sequences[sentence_index][word_index]
            checking_tag = tag_sequences[sentence_index][word_index]

            if (checking_tag == "NO_TAG_FOUND"):
                new_predicted_tag = ""
                
                # if the tag is "NO_TAG_FOUND", select the tag that gives the highest emission values
                highest_emission_value = 0
                
                for tag in tags_list:
                    current_emission_value = emission(emission_dict, tags_list, checking_word, tag)

                    if current_emission_value > highest_emission_value:
                        highest_emission_value = current_emission_value
                        new_predicted_tag = tag
                
                tag_sequences[sentence_index][word_index] = new_predicted_tag

        
    write_result(result_filename, test_word_sequences, tag_sequences)
    
    return

In [9]:
# perform prediction for the EN dataset
viterbi_second_order_prediction("EN/train", "EN/dev.in", "EN/dev.p3.out")

# evaluate prediction for the EN dataset
!python "evalResult.py" "EN/dev.out" "EN/dev.p3.out"


#Entity in gold data: 802
#Entity in prediction: 933

#Correct Entity : 535
Entity  precision: 0.5734
Entity  recall: 0.6671
Entity  F: 0.6167

#Correct Sentiment : 408
Sentiment  precision: 0.4373
Sentiment  recall: 0.5087
Sentiment  F: 0.4703


In [10]:
# perform prediction for the FR dataset
viterbi_second_order_prediction("FR/train", "FR/dev.in", "FR/dev.p3.out")

# evaluate prediction for the FR dataset
!python "evalResult.py" "FR/dev.out" "FR/dev.p3.out"


#Entity in gold data: 238
#Entity in prediction: 460

#Correct Entity : 161
Entity  precision: 0.3500
Entity  recall: 0.6765
Entity  F: 0.4613

#Correct Sentiment : 76
Sentiment  precision: 0.1652
Sentiment  recall: 0.3193
Sentiment  F: 0.2178


# Part 4
Report the precision, recall and F scores for the outputs for both datasets.\


We have tweaked the 2nd order viterbi algorithm for part 3, by doing a tag replacement for words that start with specific characters. Moreover, we have also tweaked the k values (the smoothing constant) to produce the best F scores possible.

<u>EN dataset</u>:\
Number of entities in gold data: 802\
Number of entities in prediction: 875\
\
Number of correct entities : 532\
Entity  precision: 0.6080\
Entity  recall: 0.6633\
Entity  F: 0.6345\
\
Number of correct sentiments : 415\
Sentiment  precision: 0.4743\
Sentiment  recall: 0.5175\
Sentiment  F: 0.4949\
\
<u>FR dataset</u>:\
Number of entities in gold data: 238\
Number of entities in prediction: 448\
\
Number of correct entities : 160\
Entity  precision: 0.3571\
Entity  recall: 0.6723\
Entity  F: 0.4665\
\
Number of correct sentiments : 81\
Sentiment  precision: 0.1808\
Sentiment  recall: 0.3403\
Sentiment  F: 0.2362

In [11]:
# function to assign words that start with "@?.!-", as well as words that contain the substring "http" to a default value 
def remove_username(tags, sentence):
    for i in range(len(sentence)):
        if sentence[i][0] in "@?.!-":
            tags[i] = "NO_TAG_FOUND" # or wtv tag we want it to be
        if sentence[i] in "http":
            tags[i] = "NO_TAG_FOUND" # or wtv tag we want it to be
    return tags

In [12]:
def viterbi_second_order_prediction_stop_word_removal(training_filename, test_filename, result_filename, k=1):
    training_word_sequences, training_tag_sequences = read_training_data(training_filename)
    test_word_sequences = read_test_data(test_filename)
    
    emission_dict, tags_list = create_emission_dict_tags_list(training_filename, k)
    transition_dict_second_order = create_transition_dict_second_order(training_tag_sequences)

    tag_sequences = []

    for i in range(len(test_word_sequences)):
        most_likely_tags = viterbi_second_order(test_word_sequences[i], tags_list, emission_dict, transition_dict_second_order)
        tag_sequences.append(most_likely_tags)
    
    # some words may still be tagged "NO_TAG_FOUND". For those words, select the tag that 
    # gives the highest emission value
    for sentence_index in range(0, len(test_word_sequences)):
        for word_index in range(0, len(test_word_sequences[sentence_index])):
            # check the tag that was predicted for each word
            checking_word = test_word_sequences[sentence_index][word_index]
            checking_tag = tag_sequences[sentence_index][word_index]

            if (checking_tag == "NO_TAG_FOUND"):
                new_predicted_tag = ""
                
                # if the tag is "NO_TAG_FOUND", select the tag that gives the highest emission values
                highest_emission_value = 0
                
                for tag in tags_list:
                    current_emission_value = emission(emission_dict, tags_list, checking_word, tag)

                    if current_emission_value > highest_emission_value:
                        highest_emission_value = current_emission_value
                        new_predicted_tag = tag
                
                tag_sequences[sentence_index][word_index] = new_predicted_tag

        tag_sequences[sentence_index] = remove_username(tag_sequences[sentence_index], test_word_sequences[sentence_index])

        
    write_result(result_filename, test_word_sequences, tag_sequences)
    
    return

In [13]:
# perform prediction for the EN dataset
viterbi_second_order_prediction_stop_word_removal("EN/train", "EN/dev.in", "EN/dev.p4.out", k=35)

# evaluate prediction for the EN dataset
!python "evalResult.py" "EN/dev.out" "EN/dev.p4.out"


#Entity in gold data: 802
#Entity in prediction: 875

#Correct Entity : 532
Entity  precision: 0.6080
Entity  recall: 0.6633
Entity  F: 0.6345

#Correct Sentiment : 415
Sentiment  precision: 0.4743
Sentiment  recall: 0.5175
Sentiment  F: 0.4949


In [14]:
# perform prediction for the FR dataset
viterbi_second_order_prediction("FR/train", "FR/dev.in", "FR/dev.p4.out", k=60)

# evaluate prediction for the FR dataset
!python "evalResult.py" "FR/dev.out" "FR/dev.p4.out"


#Entity in gold data: 238
#Entity in prediction: 448

#Correct Entity : 160
Entity  precision: 0.3571
Entity  recall: 0.6723
Entity  F: 0.4665

#Correct Sentiment : 81
Sentiment  precision: 0.1808
Sentiment  recall: 0.3403
Sentiment  F: 0.2362
